# /etc/rsyslog.d/50-forward.conf
# Forward all logs from Linux to Windows syslog collector
#
# Syntax:
#   *.*           = all facilities, all severity levels
#   @             = UDP (use @@ for TCP)
#   192.168.125.1 = IP of Windows log collector (Kiwi Syslog Server)
#   514           = standard syslog port

*.* @192.168.125.1:514
